// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4t4y-6SGWd2jK3cz0kv-H23x2r5zyti4',
    appId: '1:999699075378:web:b9315846593317e732872b',
    messagingSenderId: '999699075378',
    projectId: 'experta-ce200',
    authDomain: 'experta-ce200.firebaseapp.com',
    storageBucket: 'experta-ce200.firebasestorage.app',
    measurementId: 'G-SF7JSGHD4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmeb9gWLh6-dLeR7BD_iSlaPy2DIYx7n0',
    appId: '1:999699075378:android:08738b019d14b49632872b',
    messagingSenderId: '999699075378',
    projectId: 'experta-ce200',
    storageBucket: 'experta-ce200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBE1iHM3lR1J7uuf7w_OYHDMzRlFYXuTE',
    appId: '1:999699075378:ios:02de8d5400f02dce32872b',
    messagingSenderId: '999699075378',
    projectId: 'experta-ce200',
    storageBucket: 'experta-ce200.firebasestorage.app',
    iosBundleId: 'com.example.expert',
  );
}
