// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4w9iIBnOpUFuro01jMBbwt03kyVJDj5A',
    appId: '1:651672354813:web:16a7284446ac979cee6394',
    messagingSenderId: '651672354813',
    projectId: 'experta-30f9e',
    authDomain: 'experta-30f9e.firebaseapp.com',
    storageBucket: 'experta-30f9e.firebasestorage.app',
    measurementId: 'G-SNL8941N2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAImJvYzhOu_sCqqHOrVtEvvZX8hpAi5Bo',
    appId: '1:651672354813:android:ecc8e892f789c8b2ee6394',
    messagingSenderId: '651672354813',
    projectId: 'experta-30f9e',
    storageBucket: 'experta-30f9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrv9lsiri0gt9BHHxzEK1w0tdG50r2UGk',
    appId: '1:651672354813:ios:5faf51e2e6d53a2dee6394',
    messagingSenderId: '651672354813',
    projectId: 'experta-30f9e',
    storageBucket: 'experta-30f9e.firebasestorage.app',
    iosBundleId: 'com.example.expert',
  );
}
